apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: 894144679553.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp:latest
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: regcred
